### ISSUE TITLE
Browser back/forward doesn't trigger router update

### ISSUE THREAD

**Issue by stackoverfloweth** [kitbagjs/router#128]
navigating with router buttons does not trigger router update. I'm not sure how it's supposed to work, I no longer see any event listeners for `popstate`

https://github.com/kitbagjs/router/assets/6098901/23e8fb1e-5b6d-4933-ae1d-8d0f6c70afff

**Comment by pleek91** [comment]
Closed by https://github.com/kitbagjs/router/pull/131
