### ISSUE TITLE
Support file-based routing

### ISSUE THREAD

**Issue by Jogai** [kitbagjs/router#192]
Currently I use vue-router toghether with [Unplugin Vue Router](https://uvr.esm.is/). This makes it using routes already easy and painless. If kitbag would support this I could test it out in my current project to see if it has benefits over vue-router.

**Comment by pleek91** [comment]
@Jogai Thanks for creating an issue and for checking out kitbag router. The unplugin vue router is a cool project. One we're watching closely. We're not apposed to file based routing but for now its not on our immediate roadmap. If we do implement file based routing its likely to have differences from unplugin vue router's implementation. Similarly kitbag router isn't directly compatible with an existing vue router project. Though there are a lot of similarities and our goal is to make migrating from vue router to kitbag router as painless as possible.

I'm curious what features of unplugin vue router you were interested in. Did you want file based routing specifically or were you interested in some of the type safety that it offers? Does it solve some frustration you had with vue router? 

Thanks again for you're interest in this project!

**Comment by pleek91** [comment]
Closing this for now as we don't have any current plans to support file based routing. But this might come up again in the future.
