### ISSUE TITLE
Export RouterResolve type?

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#293]
From this [example](https://router.kitbag.dev/getting-started.html#type-safety-in-routerlink):

```vue
<router-link :to="(resolve) => resolve('home')">Go somewhere</router-link>
```

If the function body passed to `:to` is long (like when we need to pass a long option), it is better to move to a TS code like:

```ts
const homeUrl = (resolve) => resolve('home', ...)
```

But the issue that I don't know to  type-annotate `resolve`, because the `RouterResolve` is not exposed.

**Comment by hongquan** [comment]
Found the solution, that is, if I define the routes in _routes.ts_:

```ts
const routes = []

export const router = createRouter(routes)
```

I need to add one line at the end of file:

```ts
export type RouterResolve = typeof router.resolve
```

**Comment by pleek91** [comment]
@hongquan yep that definitely works!

Another suggestion would be to just use the router's resolve itself for the `to` prop value if you're defining it in a component context. 

```
const router = useRouter()

cont to = computed(() => router.resolve(...))
```

Since router ultimately just wants a string. The callback is just a convenience for type safety.

**Comment by hongquan** [comment]
Yes. It is shorter.

**Comment by pleek91** [comment]
Glad you were able to figure it out. And thanks for opening an issue! Please let us know if you have any feedback in general, we'd love to hear your thoughts

**Comment by hongquan** [comment]
@pleek91 I have just tried the `computed` approach. It is denied by `<RouterLink />`  because the return typed of `router.resolve` is `string`, which doesn't match `to` expectation (`Url` or callback).
