### ISSUE TITLE
"Property does not exist on type 'Writable<{}>'" when accessing params

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#294]
I defined routes as:

```ts
const roomRoute = createRoute({ path: path('/rooms/[roomId]', { roomId: Number }), name: 'room', component: RoomWrap, parent: farmRoute })

const routes = [
  ...
  roomRoute,
  ...
]
export const router = createRouter(routes, {
  base: BASE_PATH,
})
```

and in `RoomWrap.vue` component, I tried to access `roomId` params:

```ts
const route = useRoute('room')

const roomId = route.params.roomId
```

But `vue-tsc` keeps complaining:

```
Property 'roomId' does not exist on type 'Writable<{}>'
```

**Comment by pleek91** [comment]
@hongquan Did you register your router type with the register interface? 

Just want to check that first. 

https://router.kitbag.dev/getting-started.html#update-registered-router

**Comment by stackoverfloweth** [comment]
@hongquan here's a working example in stackblitz
https://stackblitz.com/~/github.com/kitbagjs/router-preview

Noice this registration in main.ts

```ts
declare module '@kitbag/router' {
  interface Register {
    router: typeof router
  }
}
```

**Comment by hongquan** [comment]
I registered, but not work. I try "kitbagjs/router-preview" and it works. Could it be `tsconfig.json`?

**Comment by pleek91** [comment]
It could be a tsconfig issue but not sure what it would be 🤔 you could try copying the tsconfig from the preview and see if that causes your project to work. 

Couple other things to check/try. 

When you call useRoute and you go to pass the name argument, does typescript suggest the names from your routes? 

Does it error if you give it a name that doesn't match your routes?

What is the type it returns for your route?

**Comment by hongquan** [comment]
Yes, TS suggests correct route name, the type of  `router` also looks correct when it show the name of the routes I passed the `createRouter`.

I have fixed this issue by removing some errornous views from the route list. I'm migrating my project from `vue-router` to `kitbag/router`, where many of my components still use `vue-router` syntax, like `:to="{ name: 'my-view' }"`. It seems that those error breaks TS type inference on `@kitbag/router` types.

**Comment by pleek91** [comment]
@hongquan ah yeah that would do it. I'm surprised it didn't give you a type error when passing in the routes themselves. Glad you figured it out! 

Hope the migration goes well!

**Comment by hongquan** [comment]
Update:

- Not fixed yet, as long as I added more route to the `routes` list, the error appears again. This added route is using a pretty innocent Vue component (without any vue-router code).

![image](https://github.com/user-attachments/assets/5f838cca-742c-4653-9086-502ac6474dc4)

![image](https://github.com/user-attachments/assets/264c43be-68a3-46b8-96d1-da3ea466bc7b)

**Comment by hongquan** [comment]
After tweaking the "kitbagjs/router-preview" example, I found that If I change from

```ts
export const router = createRouter([home, settings, profile, keys])
```

to

```ts
const routes = [home, settings, profile, keys]
export const router = createRouter(routes)
```

I can reproduce this problem.

So the tip is that the route list must be "readonly". I just need to change the declaration of the route list to

```ts
const routes = [home, settings, profile, keys] as const
```

and the problem gone 🎉

**Comment by stackoverfloweth** [comment]
@hongquan I'm glad you found a solution! 

Does your project still have router-vue installed? (Check node_modules, could be nested dependency) Because both Kitbag/Router and vue-router use declaration merging for Vue global components to register a "RouterLink" component. I could see a similar issue if your project is trying to merge both.

**Comment by hongquan** [comment]
I already removed `vue-router`, deleted *node_modules* then reinstalled dependency packages.
