### ISSUE TITLE
Expose Url type?

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#297]
Use case:
- I have some pages which require user to log-in. If an user clicks to the links, the link will redirect user to Login page, attaching the original URL, like: `/login?attempt=/control`.
- After user finishes logging-in, the Login page will extract "attempt" query paramter to redirect user to that attempted URL.

The problem is that, `router.push` requires parameter to be of `Url` type. This type is not exposed for me to implement validator for query param, to assure that the `attempt` value always be `Url`.

**Comment by stackoverfloweth** [comment]
@hongquan, I've opened a PR to export our `Url` type as well as the corresponding type guard we use `isUrl`. I will publish a new version to npm when that gets merged.

In the meantime, you should be able to satisfy typescript with your own type checking that the string you're passing is a string that starts with `http` or starts with a forward slash `/`. 

```ts
export type Url = `http://${string}` | `https://${string}` | `/${string}` | '/'
```

**Comment by stackoverfloweth** [comment]
@hongquan v0.11.1 should be what you're looking for 
https://www.npmjs.com/package/@kitbag/router/v/0.11.1
