### ISSUE TITLE
How to build breadcrumb?

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#299]
I am trying to build a breadcrumb for deep nested pages, to let user easily go to ancestor pages.

In `vue-router`, I use [`route.matched`](https://router.vuejs.org/api/interfaces/RouteLocationNormalizedTyped.html#matched) to get the URLs of the ancestor pages. But in `@kitbag/router`, there is no way. In `@kitbag/router`, the `route.matches` just return the data used for defining routes (in `routes.ts`), where `name` is of `string | undefined` type, and `path` is just a portion, not a full path.

**Comment by stackoverfloweth** [comment]
@hongquan do your breadcrumbs use `router-link`? You should be able to use the `name` property but I can see how that's not a perfect solution. You'll need to use a type guard or casting to convince TS your name is valid. It also wouldn't work for any routes that have params. 

```ts
<template v-for="match in route.matches" :key="match.id">
  <router-link :to="resolve => resolve(match.name as typeof route['name'])">{{  match.name }}</router-link>
</template>
```

Note if a match has an undefined name, it's not a navigable route. 

We will see if we can find a better solution for you

**Comment by stackoverfloweth** [comment]
@hongquan you can indeed use `router-link`, we just need a type guard to satisfy Typescript for the known name piece and we can pass `params` as well. Here's a complete working example.

```html
<template>
  <template v-for="match in matches" :key="match.id">
    <router-link :to="match">{{  match }}</router-link>
  </template>
  
  <router-view />
</template>
```

```ts
import { Url, isUrl, useRoute, useRouter } from '@kitbag/router';
import { computed } from 'vue';

const router = useRouter()
const route = useRoute()

function isRouteName(name: string | undefined): name is typeof route['name'] {
  return !!name && name !== 'NotFound'
}

const matches = computed(() => {
  return route.matches.reduce<Url[]>((matches, match) => {
    if(isRouteName(match.name)){
      const url = router.resolve(match.name, route.params)

      if(isUrl(url)){
        matches.push(url)
      }
    }

    return matches
  }, [])
})
```

Note, the check for `name !== "NotFound"` is checking that the current route is not a [rejection route](https://router.kitbag.dev/advanced-concepts/rejections.html).  Again, we have a type guard for that which we can include in the public API. For now checking the name will suffice since rejection routes use the reject type for a name.

**Comment by hongquan** [comment]
@stackoverfloweth Thank you.

Will try again some day. I canceled the "vue-router to kitbag router" migrations due to this issue and another "recursive type resolve" when building navigation bar (which I didn't have time to report).

**Comment by pleek91** [comment]
@hongquan Thanks for contributing to this project by using it and submitting issues! Sorry to hear your migration didn't succeed. We're going to keep working on making this specific use case (breadcrumbs) a good devx. 

I'm also very curious about the recursive types issue you had in your nav bar. If you have time to share that one I'd appreciate it.

**Comment by stackoverfloweth** [comment]
I'm going to reopen this as an action item for us to finish improvements to types to make this easier and then either 

A. Provide a concise snippet, possibly in docs for how to build such a component
B. Actually create a BreadCrumbs vue component exported by @kitbag/router

**Comment by hongquan** [comment]
@pleek91 Unfortunately, I cannot reproduce the "recursive type resolve" issue with the "router-preview" example.

**Comment by pleek91** [comment]
@hongquan I believe v0.12.0 should resolve this. We've made a few changes to hopefully make this work easily using `route.matches` and `router.resolve`

https://github.com/kitbagjs/router/pull/308
https://github.com/kitbagjs/router/pull/325

So this example should work without any type errors now

```ts
const router = useRouter()
const route = useRoute()

const crumbs = computed(() => {
  const urls = []

  for(const match of route.matches) {
    if(!match.name) {
      continue
    }

    const url = router.resolve(match.name, route.params)

    urls.push(url)
  }
})
```

**Comment by hongquan** [comment]
Thanks @pleek91 
I will find time to try it.

**Comment by pleek91** [comment]
@hongquan I'm going to close this issue. But let us know if you get a chance to try this out.
