### ISSUE TITLE
Component name not shown when mounting app under subfolder

### ISSUE THREAD

**Issue by hongquan** [kitbagjs/router#302]
This can be reproduced in https://github.com/kitbagjs/router-preview by modifying as following:

In _vite.config.ts_:

```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

const BASE_PATH = '/f'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), vueDevTools()],
  base: BASE_PATH,
})
```

In _router/index.ts_, change the `createRouter` line to:

```ts
export const router = createRouter([home, settings, profile, keys], {
  base: import.meta.env.BASE_URL
})
```

Now, all pages are shown as `routerView` when seeing in VueDevTools:

![image](https://github.com/user-attachments/assets/9bf0c32b-42dc-48cd-ae08-c2fb72bfe327)

**Comment by pleek91** [comment]
@hongquan But it works fine if you don't use a base path? 🤔

**Comment by hongquan** [comment]
It works without using base path.

**Comment by stackoverfloweth** [comment]
@hongquan the version you're looking for is v0.11.2
https://www.npmjs.com/package/@kitbag/router/v/0.11.2
